name: ${name}
version: ${version}
main: ${mainClass}
api-version: 1.16
authors: [SecretX]
description: Links and control the flows of items between chests
website: https://github.com/SecretX33

commands:
  zapchest:
    description: ${name}
    usage: /<command> <sub> [parameters]
    aliases: [zap, zc]

permissions:

  zapchest.*:
    description: Gives access to all ${name} commands. Default to players with op.
    default: op
    children:
      zapchest.reload: true
      zapchest.groups.*: true

  zapchest.groups.*:
    description: Gives access to all zapchest groups features.
    default: false
    children:
      zapchest.groups.create: true
      zapchest.groups.inviteothers: true
      zapchest.groups.joinothers: true
      zapchest.groups.listgroups: true
      zapchest.groups.addstorage: true

  zapchest.reload:
    description: Allows one to reload all plugin configurations.
    default: false

  zapchest.groups.create:
    description: Allows one to create zapchest groups to link chests, as well as adding or removal material or material categories to/from owned groups.
    default: false

  zapchest.groups.inviteothers:
    description: Allows one to invite other people to join their groups.
    default: false

  zapchest.groups.joinothers:
    description: Allows one to be invited to join other people groups.
    default: false

  zapchest.groups.listgroups:
    description: Allows one to be list all groups the player is currently in.
    default: false

  zapchest.groups.addstorage:
    description: Allows one to add and remove storage from groups they own.
    default: false
